### ISSUE TITLE
Images used for testing

### ISSUE THREAD

**Issue by Leanny** [fga401/AutoTableTurf#3]
Hello, I am trying to fine-tune the openCV parameters for my environment and figured that your unittests are quite good for testing various things. Unfortunately, I have no idea what some of the tests try to detect based on the name alone. Would it be possible to share the screenshots you use for testing, so I can get an idea with what kind of screenshots I need to replace them for the fine-tuning process?

**Comment by fga401** [comment]
uploaded test images to the branch `test`
