### ISSUE TITLE
Sys-botbase support?

### ISSUE THREAD

**Issue by UltraMoonTrainer** [fga401/AutoTableTurf#5]
hello, i was wondering if you would be able to make another version that would work with sys-botbase too, since this seems to fundamentally do a similar thing from that software. Would be really cool if you could so CFW users can have an easier method :)
## https://github.com/olliz0r/sys-botbase

**Comment by fga401** [comment]
sorry, I don't have such plan recently as I'm not a CFW user. 

but I think my interfaces are easy to integrate with sys-botbase. you will just need to implement these two interfaces:
- https://github.com/fga401/AutoTableTurf/blob/master/controller/interface.py
- https://github.com/fga401/AutoTableTurf/blob/master/capture/interface.py

**Comment by UltraMoonTrainer** [comment]
oh alright thank you very much!
