### ISSUE TITLE
Corrupt JPEG data Error Causes AI to Stop

### ISSUE THREAD

**Issue by eangele1** [fga401/AutoTableTurf#7]
## Expected Behavior:
The AI program should run and continue as normal despite any errors.

## Actual Behavior:
When running the program, it eventually encounters an OpenCV error, resulting in bringing the AI to a halt in the middle of the sequence.

## Error Message:
This is from the portal terminal.
``` javascript
Corrupt JPEG data: premature end of data segment
[2023-09-11 02:41:33,370] [DEBUG] detection.hands_cursor: return=-1
[2023-09-11 02:41:33,415] ERROR in app: Exception on /home/run [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.10/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ezer/Desktop/AutoTableTurf-master/portal/home/home.py", line 71, in run
    manager.run(profile=Profile.from_json(profile), closer=closer, debug=debug)
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/tableturf.py", line 99, in run
    self.run_once(task.deck, closer=task_closer, debug=debug)
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/tableturf.py", line 119, in run_once
    status = self.__get_status(round)
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/tableturf.py", line 193, in __get_status
    hands = self.__multi_detect(detection.hands)(debug=self.__session['debug'])
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/tableturf.py", line 50, in wrapper
    current = detect_fn(self.__capture(), *args, **kwargs)
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/detection/card.py", line 129, in hands
    cards = [Card(grids[i], costs[i]) for i in range(4)]
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/manager/detection/card.py", line 129, in <listcomp>
    cards = [Card(grids[i], costs[i]) for i in range(4)]
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/model/card.py", line 104, in __init__
    self.__patterns = [Pattern(np.rot90(grid, i)) for i in range(4)]
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/model/card.py", line 104, in <listcomp>
    self.__patterns = [Pattern(np.rot90(grid, i)) for i in range(4)]
  File "/home/ezer/Desktop/AutoTableTurf-master/tableturf/model/card.py", line 24, in __init__
    self.__offsets = indexes - indexes[0][np.newaxis, ...]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

## Environment:
Operating System: Linux Ubuntu 22.04.3 LTS
Machine: Dell Inc. Inspiron 13-7359
Capture Card: Razer Ripshaw HD

## Additional Information:
I'm running the program on a Dell Inspiron laptop with the Ubuntu OS. Everything executes as normal until a little after when the program runs for a good while. I'm assuming the error could be because of the Razer Ripshaw HD capture card that I'm using. It still occasionally flickers after I've done all that I could to get it stabilized. Room for improvement is accepted.

Please let me know if you need any further information or if there's a specific fix for this problem. Thank you!

**Comment by fga401** [comment]
It seems that it cannot recognize the card.

For further debugging:
1. Does your deck contain any upgraded cards that have sparkling special effects?
2. Can you share your whole deck?
3. Please enable the debug mode, open `http://localhost:5000/debug/hands.image` and `http://localhost:5000/debug/hands.color_mask`, and share the last screenshot from those two pages.

Also, you (I probably will pick it up when I am free) can try to catch the exception and return an empty card if it fails to recognize the card. I guess the built-in retry mechanism will handle the failure.

**Comment by eangele1** [comment]
Thanks! 

First, the cards within the deck I'm using do not have any upgrades, although I intend to upgrade them in the near future.

Second, I have been using the same deck as shown in your first demo video, but I will show it again for context.

Deck:
<img src="https://github.com/fga401/AutoTableTurf/assets/32885507/8ead1a89-08f7-4840-ad48-72041259aefe" alt="hands.image" width="75%" height="75%">

Finally, I have re-run the program and enabled the debugger. These were the last two screenshots captured before the error popped up again. It most likely is a capture card issue, but would be a good idea to see how this error can be prevented.

hands.image:
<img src="https://github.com/fga401/AutoTableTurf/assets/32885507/867b5bd9-332c-4cdd-ad8b-72a11d77f431" alt="hands.image" width="75%" height="75%">

hands.color_mask:
<img src="https://github.com/fga401/AutoTableTurf/assets/32885507/3f44e977-a548-41da-9ca6-4aa0d96a3ad7" alt="hands.color_mask" width="75%" height="75%">

My initial thought was also to use a try-catch exception to handle the error. However, I'm unaware as to which file I need to edit in order to handle the error. In addition, my initial intuition for fixing this was either to recapture the frame or have the AI restart the round, but I'm not sure. Let me know your thoughts on this.

**Comment by fga401** [comment]
I am sure it's a capture card issue now. It provided a broken image for recognition.

https://github.com/fga401/AutoTableTurf/blob/c809b00b4b640c15360e47cf532533f9c583fff3/tableturf/manager/tableturf.py#L45
This function performs retrying. It uses two frames (with 0.1s intervals) for recognition. If both of them return the same result, it will return the result, otherwise, it will use the next frame and try to do recognition again.
So if your capture card does not provide two consecutive images, this function will handle the failure.

What you will need to do is only to catch the exception in the recognition function.
https://github.com/fga401/AutoTableTurf/blob/c809b00b4b640c15360e47cf532533f9c583fff3/tableturf/manager/detection/card.py#L57

I guess you can find some clues in your stack trace.

**Comment by eangele1** [comment]
So I've recently been able to eliminate the error but by using a USB 3.0 cable instead of the one the capture card came with. No code has been modified. I've encountered another error that I believe I'll make a separate issue for. Should I keep this issue open or would you like me to close it?

**Comment by fga401** [comment]
let's close this one and open a new one.
